#!/bin/sh
t_script inache -stop
SITE_PATH=/var/www/nodeStatic/inache
REPO_PATH=/var/www/repos/inache.git
rm -rf $SITE_PATH && mkdir $SITE_PATH && cp /var/www/repos/inache-files/db.json $SITE_PATH && cp /var/www/repos/inache-files/env.local.js $SITE_PATH
git --work-tree=$SITE_PATH --git-dir=$REPO_PATH checkout -f
cd $SITE_PATH && npm i && npm run build && t_script inache -start
